### ISSUE TITLE
As a user, I want to be able to add my own text to a chosen meme template, so that I can customize the meme to my liking. 

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-client#42]
## Acceptance Criteria
- [x] sopra-fs23-group-13/meme-it-client#20
- [x] sopra-fs23-group-13/meme-it-client#21
- [x] sopra-fs23-group-13/meme-it-client#22
- [x] sopra-fs23-group-13/meme-it-client#19
- [x] sopra-fs23-group-13/meme-it-server#104

## Tests
- [x] Enter text into each field and verify that it is displayed on the meme template.
- [x] Change the font style, size, and color of the text and verify that the changes are reflected on the meme template.
