### ISSUE TITLE
As a user, I want to be able to look at a leaderboard after each round and also after the final round ends.

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-client#43]
## Acceptance criteria

- [ ] sopra-fs23-group-13/meme-it-client#15
- [ ] sopra-fs23-group-13/meme-it-client#16
- [ ] sopra-fs23-group-13/meme-it-client#17
- [ ] sopra-fs23-group-13/meme-it-client#18

## Tests

- [ ] Leaderboards display differently depending on whether a normal or the final round ended.
- [ ] The leaderboard should automatically go away after a given time, to allow for a new round to start.
- [ ] A player should not be able to determine the username of a meme creator during the voting phase.
