### ISSUE TITLE
As a user, I want to be greeted with an intuitive main page when opening the website. This means that even as a first time user I should be able to understand what buttons to click in order to achieve my goals (joining a lobby etc.

### ISSUE THREAD

**Issue by M-Schurr** [sopra-fs23-group-13/meme-it-client#44]
## Acceptance Criteria
- [x] sopra-fs23-group-13/meme-it-client#5
user stories
- [x] sopra-fs23-group-13/meme-it-client#4
- [x] sopra-fs23-group-13/meme-it-client#2

## Tests
- [ ] First time users are able to navigate the main page without any previous knowledge of the game
- [ ] All buttons contain explicit and clear label
- [ ] Username input field contains a useful label and hint
- [ ] First time users easily understand how to start a new game
- [ ] Existing users easily understand where to start optional tutor
