### ISSUE TITLE
As a new user, I want to be greeted with an uncomplicated optional tutorial when visiting the website.

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-client#45]
## Acceptance criteria

- [x] sopra-fs23-group-13/meme-it-client#34
- [x] sopra-fs23-group-13/meme-it-client#36
- [x] sopra-fs23-group-13/meme-it-client#37
- [x] sopra-fs23-group-13/meme-it-client#38

## Tests

- [x] User should be able to exit tutorial at any step.
- [x] User should be able to skip tutorial.

**Comment by danielLutziger** [comment]
https://github.com/sopra-fs23-group-13/meme-it-client/pull/163
