### ISSUE TITLE
As a user, I want to be able to chat with other players while waiting in the lobby and during the game.

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-client#48]
## Acceptance criteria

- [x] sopra-fs23-group-13/meme-it-server#37
- [x] sopra-fs23-group-13/meme-it-server#82
- [x] sopra-fs23-group-13/meme-it-client#28

## Tests

- [ ] A player in a lobby can not chat with players from a different one.
- [ ] Chats should only be displayed in game lobbies and never on the main page.

**Comment by danielLutziger** [comment]
[closed by #118
](https://github.com/sopra-fs23-group-13/meme-it-server/pull/118)
https://github.com/sopra-fs23-group-13/meme-it-client/pull/65
