### ISSUE TITLE
As a user, I want to be able to view a list of public lobbies that I can join so I can play without friends.

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-client#49]
## Acceptance Criteria
- [x] sopra-fs23-group-13/meme-it-client#23
- [x] sopra-fs23-group-13/meme-it-client#26
- [x] sopra-fs23-group-13/meme-it-server#69
- [ ] sopra-fs23-group-13/meme-it-server#70

## Tests
- [ ] Joining a game that isn't full should take the player into the lobby.
- [ ] Joining a game that is full should return an alert to the player.
