### ISSUE TITLE
As a user, during each round I want to be able to create my own meme and afterwards look at and rate each individual meme submitted by a player.

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-client#54]
## Acceptance criteria

- [ ] sopra-fs23-group-13/meme-it-server#76
- [ ] sopra-fs23-group-13/meme-it-client#12
- [ ] sopra-fs23-group-13/meme-it-server#78
- [ ] sopra-fs23-group-13/meme-it-server#66
- [ ] sopra-fs23-group-13/meme-it-server#67

## Tests

- [ ] When a player's own meme is shown, the rating buttons should be disabled.
- [ ] A player leaving during any point in time in the round shouldn't influence other players.

**Comment by weberlii** [comment]
59e8243894defa15ff6de28944ef90553d3ca272
